import { createContext, useContext, type ReactNode } from 'react'
import type { CityPack, HistoricalLayer, Locale } from '../types'

const copy = {
  'zh-TW': {
    cityVersionControl: '城市版本誌 · Urban version control', studyCity: '研究城市', researchScope: '研究範圍', historicalLayers: 'Historical layers', chooseVersion: '選擇版本', currentRoads: 'OpenStreetMap 道路', currentlyShowing: '目前顯示', layerSource: '圖層來源', openSourceMap: '開啟中研院圖台 ↗',
    language: '語言', method: '資料與方法', view: '版面', timeline: '版本欄', inspector: '分析欄', contextLayer: '脈絡圖層', monuments: '法定古蹟', analysis: '分析模式', compare: '地圖比較', lostAlleys: '巷弄痕跡', film: '變化膠卷', stitchPoints: '城市縫合點',
    historyMap: '歷史圖資', modernRoads: '現代道路', roadsAvailable: '條道路', clickSelect: '點擊選擇', clickLocate: '點擊定位', clickInspect: '點擊查看', alleyEndpoint: '巷道端點', endpoint: '端點', distanceToRoad: '距選定道路約 {value}m', directAbout: '直線約 {value}m', dragDivider: '拖曳調整歷史與現代地圖比較界線', mapSelectHint: '點綠色道路，或從右側搜尋', selectRoadFirst: '先選擇一條道路，再產生候選點', filmHint: '點擊地圖任意位置，建立城市變化膠卷',
    selectRoad: '選一條道路', selectRoadHelp: '直接點地圖上的綠色道路，或用名稱搜尋。', results: '搜尋結果', suggested: '建議道路', selectable: '條可選', searchPlaceholder: '輸入道路名稱…', noRoad: '目前研究區找不到這條道路。', suggestionNote: '建議清單依研究區內的 OSM 中心線總長排列，不代表影響程度。', boundary: '這是歷史圖資比較工具，不是法定界址或因果判定。', change: '更換', totalLength: '研究區內總長', osmSegments: 'OSM 路段', oneway: '單行標記', oneWay: '單行', notOneWay: '非單行', unknown: '未標註', sourceUnknown: '來源未回報',
    evidenceSummary: '證據摘要', computed: '程式計算 · 非 AI 影像判讀', summaryIntro: '快速閱讀目前資料能支持的訊號，再回到地圖查證。', summaryCompare: '{year} 圖層與今日道路已對齊，可拖曳中線比較；系統尚未自動辨識歷史圖中的線條。', summaryAlleys: '步行路網中找到 {count} 個朝向此道路、但在接近前中止的形態候選。', summaryStitches: '找到 {count} 組近距離端點，其中 {disconnected} 組在目前路網中未連通。', summaryCulture: '道路 500 公尺內有 {count} 筆官方登錄古蹟，可作為文化脈絡線索。', summaryLimit: '這些是調查線索，不證明歷史因果、通行權、所有權或施工可行性。',
    currentComparison: '目前比較', comparisonHelp: '拖曳地圖中線，沿著橘色道路查看舊街廓方向與今日路網的差異。', orangeWarning: '橘色帶是視覺提示，不代表法定道路範圍或歷史因果。', culturalContext: '道路文化脈絡', places500: '處 / 500m', culturalHelp: '由道路中心線量測至文化部登錄古蹟座標，協助辨識周邊文化脈絡；不代表兩者有歷史因果。', noCulture: '此道路中心線 500 公尺內沒有本資料集的登錄古蹟。', morePlaces: '另有 {count} 處，可在地圖上查看。', officialFetched: '官方資料擷取：{date}',
    alleyCandidates: '巷弄痕跡候選', morphologySignal: '形態訊號 · 待歷史圖確認', alleyHelp: '找出朝向{road}、卻在接近道路前中止的 OSM 步行路網端點。點選候選後，用歷史圖判讀過去是否曾經連續。', distanceApproach: '距道路 {distance}m · 朝向度 {score}%', noAlleys: '目前步行路網快照中沒有符合門檻的端點。這不表示此處不存在歷史連接。', candidateWarning: '候選不是歷史事實；端點可能來自門禁、私人通道、高差或 OSM 繪製方式。快照：{date}',
    connectivityCandidate: '連通性候選 · 不代表可施工', stitchHelp: '配對{road}兩側距離很近的端點，檢查目前具名路網是否需要明顯繞行。', networkDisconnected: '路網未連通', networkDistance: '路網 {distance}m / {ratio}×', noStitches: '目前沒有符合門檻的兩側端點組合。可更換道路繼續檢查。', stitchWarning: '候選不代表公共通行權、土地所有權、無高差障礙或工程可行性。快照：{date}', whyFlagged: '為什麼被標記', directGap: '端點直線距離', currentNetwork: '目前路網', interpretation: '如何判讀', stitchInterpretation: '這條紫色虛線是兩個端點之間的幾何假設。請回到歷史圖檢查是否存在過去路徑、街廓邊界或實體障礙。', notProof: '它不證明', stitchNotProof: '此處可以通行、土地可取得，或值得興建連接。',
    dataLimits: '資料與限制', derivedFacts: '線長與路段數由目前 OSM 快照程式推導。', roadDataTime: '道路資料時間', citySnapshot: '城市快照', walkSnapshot: '步行路網快照', monumentSnapshot: '全臺古蹟快照', ways: '個 way', records: '筆', license: '授權', provenanceLimit: '目前無法由這些資料得知道路開闢年份、所有權、法律界址或殘餘地塊成因。', inspectOsm: '檢查 OSM 資料來源', inspectCulture: '檢查文化資產資料來源',
    filmTitle: '城市變化膠卷', samePosition: '相同位置與比例', closeFilm: '關閉城市變化膠卷', filmCaveat: '膠卷只把同一座標並排，圖種、比例尺、測繪目的與配準誤差不同；視覺差異不等於同年發生的都市事件。',
    methodology: 'Methodology · v0.3', methodTitleA: '不是把舊地圖疊上去，', methodTitleB: '而是建立可驗證的城市版本差異。', methodLead: 'City Diff 把{name}的歷史圖資視為一連串「commit」。系統只呈現可以追溯來源的資料與形態候選，避免從視覺重疊直接跳到因果結論。', source: '載入原始版本', sourceDetail: '中研院 WMTS 歷史影像、OSM 道路與步行路網快照。', derive: '建立形態候選', deriveDetail: '合併同名 way，計算端點、朝向、路網距離與繞行倍率。', interpret: '保留人工判讀', interpretDetail: '以滑動比較與變化膠卷檢查候選，不把幾何關係直接視為歷史事實。', completed: '已完成', reproducible: '可重現的候選生成', reproducibleDetail: '真實歷史圖層、道路端點、縫合候選、文化資產、來源與快照日期。', needsResearch: '仍需研究', autoRecognition: '歷史線條自動辨識', autoRecognitionDetail: '目前由人檢查歷史圖；下一階段才測試線條分割、配準誤差與驗證紀錄。', noClaim: '不會宣稱', noCausality: '單一資料可證明因果', noCausalityDetail: '道路造成某地塊、空地目前閒置、土地可以開發，都需要額外證據。', researchQuestion: '{name}研究問題', close: '關閉', dataLoadFailed: '資料載入失敗。請重新整理或稍後再試。',
  },
  en: {
    cityVersionControl: 'Urban version control', studyCity: 'Study city', researchScope: 'Study area', historicalLayers: 'Historical layers', chooseVersion: 'Choose a version', currentRoads: 'OpenStreetMap roads', currentlyShowing: 'Active layer', layerSource: 'Layer source', openSourceMap: 'Open Academia Sinica map ↗',
    language: 'Language', method: 'Data & method', view: 'Layout', timeline: 'Versions', inspector: 'Analysis', contextLayer: 'Context layer', monuments: 'Registered monuments', analysis: 'Analysis mode', compare: 'Map compare', lostAlleys: 'Alley traces', film: 'Change film', stitchPoints: 'Stitch points',
    historyMap: 'Historical map', modernRoads: 'Current roads', roadsAvailable: 'roads', clickSelect: 'Click to select', clickLocate: 'Click to locate', clickInspect: 'Click to inspect', alleyEndpoint: 'Alley endpoint', endpoint: 'Endpoint', distanceToRoad: 'About {value}m from selected road', directAbout: 'About {value}m direct', dragDivider: 'Drag to adjust the historical/current comparison', mapSelectHint: 'Select a green road or search on the right', selectRoadFirst: 'Select a road before generating candidates', filmHint: 'Click anywhere to create a change film',
    selectRoad: 'Select a road', selectRoadHelp: 'Click a green road on the map or search by name.', results: 'Search results', suggested: 'Suggested roads', selectable: 'available', searchPlaceholder: 'Search road name…', noRoad: 'No matching road in this study area.', suggestionNote: 'Suggestions are ranked by total OSM centerline length, not significance.', boundary: 'This is a historical-map comparison tool, not a legal boundary or causal determination.', change: 'Change', totalLength: 'Length in study area', osmSegments: 'OSM segments', oneway: 'One-way tag', oneWay: 'One-way', notOneWay: 'Not one-way', unknown: 'Not tagged', sourceUnknown: 'Not reported',
    evidenceSummary: 'Evidence summary', computed: 'Computed · not AI image reading', summaryIntro: 'Start with signals supported by the current data, then verify them on the map.', summaryCompare: 'The {year} layer is aligned with current roads for swipe comparison; historical lines are not automatically recognized.', summaryAlleys: 'The walking network contains {count} morphology candidates that approach this road but stop nearby.', summaryStitches: '{count} nearby endpoint pairs were found; {disconnected} are disconnected in the current network.', summaryCulture: '{count} officially registered monuments lie within 500m and provide cultural-context clues.', summaryLimit: 'These are investigation leads—not proof of historical causation, access rights, ownership, or buildability.',
    currentComparison: 'Current comparison', comparisonHelp: 'Drag the divider and follow the orange road to compare historic block directions with today’s network.', orangeWarning: 'The orange band is a visual cue, not a legal road boundary or proof of historical causation.', culturalContext: 'Cultural context', places500: 'within 500m', culturalHelp: 'Distances are measured from the road centerline to Ministry of Culture monument coordinates. Proximity does not establish historical causation.', noCulture: 'No registered monument in this dataset lies within 500m of the road centerline.', morePlaces: '{count} more are visible on the map.', officialFetched: 'Official data fetched: {date}',
    alleyCandidates: 'Alley-trace candidates', morphologySignal: 'Morphology signal · verify on historic maps', alleyHelp: 'Find OSM walking-network endpoints that face {road} but stop before reaching it. Select one and inspect historic maps for earlier continuity.', distanceApproach: '{distance}m from road · {score}% alignment', noAlleys: 'No endpoints meet the current thresholds. This does not prove that no historical connection existed.', candidateWarning: 'Candidates are not historical facts; endpoints may reflect gates, private paths, elevation, or OSM mapping. Snapshot: {date}',
    connectivityCandidate: 'Connectivity candidate · not a construction proposal', stitchHelp: 'Pair nearby endpoints on opposite sides of {road} and test whether the named network requires a substantial detour.', networkDisconnected: 'Network disconnected', networkDistance: 'Network {distance}m / {ratio}×', noStitches: 'No endpoint pairs meet the current thresholds. Try another road.', stitchWarning: 'Candidates do not establish public access, ownership, barrier-free passage, or engineering feasibility. Snapshot: {date}', whyFlagged: 'Why it was flagged', directGap: 'Direct endpoint gap', currentNetwork: 'Current network', interpretation: 'How to read it', stitchInterpretation: 'The purple dashed line is a geometric hypothesis between two endpoints. Check the historic map for an earlier path, block edge, or physical barrier.', notProof: 'It does not prove', stitchNotProof: 'that passage is legal, land is available, or a connection should be built.',
    dataLimits: 'Data & limitations', derivedFacts: 'Lengths and segment counts are derived from the current OSM snapshot.', roadDataTime: 'Road data date', citySnapshot: 'City snapshot', walkSnapshot: 'Walking-network snapshot', monumentSnapshot: 'Taiwan monument snapshot', ways: 'ways', records: 'records', license: 'License', provenanceLimit: 'These data do not establish road construction dates, ownership, legal boundaries, or the causes of residual parcels.', inspectOsm: 'Inspect OSM source', inspectCulture: 'Inspect cultural-asset source',
    filmTitle: 'Urban change film', samePosition: 'same position and scale', closeFilm: 'Close change film', filmCaveat: 'Frames share a coordinate, but map type, scale, survey purpose, and registration error differ. A visual difference is not evidence of an event in that exact year.',
    methodology: 'Methodology · v0.3', methodTitleA: 'Not simply overlaying old maps, ', methodTitleB: 'but building inspectable urban version differences.', methodLead: 'City Diff treats historical maps of {name} as a sequence of commits. It presents traceable sources and morphology candidates without turning visual overlap into a causal claim.', source: 'Load source versions', sourceDetail: 'Academia Sinica WMTS imagery plus OSM road and walking-network snapshots.', derive: 'Derive candidates', deriveDetail: 'Merge same-name ways and calculate endpoints, alignment, network distance, and detour ratios.', interpret: 'Keep humans in the loop', interpretDetail: 'Use swipe comparison and change film to inspect candidates instead of treating geometry as historical fact.', completed: 'Implemented', reproducible: 'Reproducible candidate generation', reproducibleDetail: 'Real historical layers, road endpoints, stitch candidates, cultural assets, provenance, and snapshot dates.', needsResearch: 'Needs research', autoRecognition: 'Historical line recognition', autoRecognitionDetail: 'Maps are currently interpreted by people; line segmentation, registration error, and validation records remain future research.', noClaim: 'Not claimed', noCausality: 'One dataset proves causation', noCausalityDetail: 'Parcel formation, vacancy, and development rights require additional evidence.', researchQuestion: '{name} research question', close: 'Close', dataLoadFailed: 'Data failed to load. Refresh the page or try again later.',
  },
} as const

type CopyKey = keyof typeof copy['zh-TW']
type Variables = Record<string, string | number>

const I18nContext = createContext<{ locale: Locale; t: (key: CopyKey, variables?: Variables) => string }>({
  locale: 'zh-TW',
  t: (key) => copy['zh-TW'][key],
})

export function I18nProvider({ locale, children }: { locale: Locale; children: ReactNode }) {
  const t = (key: CopyKey, variables: Variables = {}) => translate(locale, key, variables)
  return <I18nContext.Provider value={{ locale, t }}>{children}</I18nContext.Provider>
}

export function translate(locale: Locale, key: CopyKey, variables: Variables = {}) {
  return Object.entries(variables).reduce(
    (value, [name, replacement]) => value.replaceAll(`{${name}}`, String(replacement)),
    copy[locale][key] as string,
  )
}

export function useI18n() {
  return useContext(I18nContext)
}

export const cityName = (city: CityPack, locale: Locale) => locale === 'en' ? city.nameEn : city.name
export const cityStudyArea = (city: CityPack, locale: Locale) => locale === 'en' ? city.studyAreaEn : city.studyArea
export const cityDescription = (city: CityPack, locale: Locale) => locale === 'en' ? city.descriptionEn : city.description
export const cityQuestion = (city: CityPack, locale: Locale) => locale === 'en' ? city.researchQuestionEn : city.researchQuestion
export const layerTitle = (layer: HistoricalLayer, locale: Locale) => locale === 'en' ? layer.titleEn : layer.title
export const layerDescription = (layer: HistoricalLayer, locale: Locale) => locale === 'en' ? layer.descriptionEn : layer.description
